[features]
seeds = false
[programs.localnet]
mysolapp = "5jFPiEbfu1uoo3Dszzf7sgz5VQmfsBzacz7nRzX4U1L"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/mb/code/rust/solana/wallets/rahasak.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
